disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - file_length
  - empty_count
  - identifier_name
  - empty_enum_arguments

opt_in_rules:

excluded:
  - Carthage
  - Pods

force_cast: warning

force_try:
  severity: warning

line_length: 450

cyclomatic_complexity: 14

function_body_length:
    - 80 # warning
    - 100 # error

type_body_length:
  - 450
  - 500

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 50
  excluded: iPhone

identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"

large_tuple:
  warning: 4
  error: 5

function_parameter_count:
  warning: 7
  error: 8

identifier_name:
    allowed_symbols: "_"
    min_length: 2
    max_length:
        warning: 90
        error: 1000
    excluded:
        - id
